FROM alpine:3.19.2

RUN apk update && apk add mariadb && apk add mariadb-client

COPY ./conf/my.cnf.d /etc/my.cnf.d
COPY ./tools ./tools

RUN chmod +rwx ./tools/mariadb.sh

EXPOSE 3306

ENTRYPOINT ["./tools/mariadb.sh"]
