FROM alpine:3.19.2

RUN apk update && apk add vsftpd && apk add dumb-init

COPY ./conf/vsftpd.conf /etc/vsftpd/vsftpd.conf
COPY ./tools ./tools

RUN chmod +rwx ./tools/ftp.sh

EXPOSE 2121
EXPOSE 50001-50005

ENTRYPOINT ["./tools/ftp.sh"]
