FROM alpine:3.19.2

RUN apk update && apk add php83 && apk add php83-fpm && apk add php83-mysqli && apk add php83-phar && \
	apk add php83-mbstring && apk add php83-tokenizer && apk add php83-pecl-redis && apk add php83-ctype && \
	apk add curl && curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
	chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

COPY ./conf/www.conf /etc/php83/php-fpm.d/www.conf
COPY ./tools ./tools

RUN chmod +rwx ./tools/wordpress.sh
RUN ln -s /usr/bin/php83 /usr/bin/php
EXPOSE 9000

ENTRYPOINT ["./tools/wordpress.sh"]
